### ISSUE TITLE
Not really an issue, but I like your avatar so much!

### ISSUE THREAD

**Issue by ReneFroger** [emacsfodder/emacs-bubbleberry-theme#6]
Sorry if it's bothering you, but I really like your avatar. Where did you get it, if I might ask?

**Comment by jasonm23** [comment]
It's made using a thing called the Simpsons character maker, which I think has now disappeared from the web.   It's the same thing Tarsius used to make his.

There is a slim chance that I have a copy of the site backed up on one of my laptops, I'll check for you today.

**Comment by jasonm23** [comment]
Hi I found it, email me on GitHub username at gmail.  I'll ping a tar / zip back to you.

**Comment by ReneFroger** [comment]
That's awesome, thanks for looking it up! I would love to try it out.
I will e-mail you now. :

**Comment by ReneFroger** [comment]
That's awesome, I would love to try it out! I will e-mail you now :+1:

**Comment by ReneFroger** [comment]
We're e-mailing now. So I will close this issue, thanks for the support by the way!
