### ISSUE TITLE
font-lock-negation-char-face should be some colour other than black

### ISSUE THREAD

**Issue by cbowdon** [emacsfodder/emacs-bubbleberry-theme#7]
Hey, I love this theme, thanks for making it. Can I suggest a small change? Currently font-lock-negation-char-face is very close to the background color, which can be pretty confusing. I've changed it to a lilac colour locally - I don't know if that's the best choice as I know nothing about design but it's more readable.

I'd also like to tweak the highlight colour so it's not black (again I find it hard to see) but editing the obviously black highlight face didn't seem to make a difference. Any suggestions?

Thanks

**Comment by jasonm23** [comment]
> I know nothing about design but it's more readable.

For a theme the essence of design should be readability, comfort and simply the pleasure of using a particular set of colors.

I'm not sure the best way to proceed, generally speaking I don't use this theme personally, however it does have a userbase (how active I couldn't say.)

It would probably be worth simply modifying the theme and keeping your own fork maintained.

It sounds like the choices you made suit you well, if you need specific advice on something let me know.

**Comment by jasonm23** [comment]
You can definitely submit pull requests if you make changes which you think will benefit others.

**Comment by cbowdon** [comment]
Fair enough I'll just stick with my local fork. Cheers!
